### ISSUE TITLE
Error: Authentication tag does not match tag length.

### ISSUE THREAD

**Issue by lacabra** [scrtlabs/enigma-contract#154]
**Describe the bug**
When running the *Genesis Game client* for about 10 minutes, it throws the following error, which is caused by the EnigmaJS library:

```
Waiting. Current Task Status is 1
Waiting. Current Task Status is 2
(node:36128) UnhandledPromiseRejectionWarning: Error: Authentication tag does not match tag length.
    at modes.gcm.start (/home/eng-user/genesis-game-client/node_modules/node-forge/lib/cipherModes.js:559:13)
    at forge.cipher.BlockCipher.BlockCipher.start (/home/eng-user/genesis-game-client/node_modules/node-forge/lib/cipher.js:158:13)
    at Object.decryptMessage (/home/eng-user/genesis-game-client/node_modules/enigma-js/lib/enigma-js.node.min.js:1:703779)
    at e.<anonymous> (/home/eng-user/genesis-game-client/node_modules/enigma-js/lib/enigma-js.node.min.js:1:725224)
    at tryCatch (/home/eng-user/genesis-game-client/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/home/eng-user/genesis-game-client/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (/home/eng-user/genesis-game-client/node_modules/regenerator-runtime/runtime.js:97:21)
    at be (/home/eng-user/genesis-game-client/node_modules/enigma-js/lib/enigma-js.node.min.js:1:714463)
    at s (/home/eng-user/genesis-game-client/node_modules/enigma-js/lib/enigma-js.node.min.js:1:714666)
    at /home/eng-user/genesis-game-client/node_modules/enigma-js/lib/enigma-js.node.min.js:1:714727
    at new Promise (<anonymous>)
    at e.<anonymous> (/home/eng-user/genesis-game-client/node_modules/enigma-js/lib/enigma-js.node.min.js:1:714607)
    at e.n.value (/home/eng-user/genesis-game-client/node_modules/enigma-js/lib/enigma-js.node.min.js:1:725359)
    at GenesisClient.fetchOutput (/home/eng-user/genesis-game-client/src/genesis_client.js:76:60)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:36128) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:36128) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Expected behavior**
This should not error out.

**Comment by guix77** [comment]
I've been on a probably related issue for an hour now.

I'm having this issue on my fork of the example frontend here : https://blog.enigma.co/getting-started-with-enigma-a-front-end-demo-for-dapps-bc694d3d81b9

It occurs only when I use `await this.props.enigma.decryptTaskResult(task)`. It does not depend on the uptime of the docker containers. `computeTask` and `getTaskRecordStatus` are fine.

**Comment by lacabra** [comment]
Thanks @guix77. After some investigation, I now know what is causing it, and I am working on a fix, which will likely take a few hours to get through. ETA in about 6 hours from now.

In my case, I'm running a network with 4 nodes, where this is not an issue most of the time. It appears randomly, in one about 400 computations. The computation runs successfully, but it happens around an epoch transition, where the other nodes are busy handling the epoch change, and the results don't have time to propagate to the node that the client will be requesting the results. So when the client requests the result from the network, the worker that responds don't have them yet, and warns:
```
p2p_1       | [Tue Oct 01 2019 17:02:35 GMT+0000 (Coordinated Universal Time)] INFO [PROXY_DISPATCH] error getting result NotFoundError: Key not found in database [123]
```
But the client doesn't handle the `null` value any differently, and tries to decrypt, at which point the EnigmaJS throws the above error because it cannot handle a `null` value.

In your case (because you are running with only 1 node, and your setup should be more robust), there may be other problems that we saw in the past that are now fixed, but those fixes have not been propagated to the `stable` version. The following will likely fix your issue (which will use more recent docker images that will be released soon)

1. Edit the following line in your project `.env` file (in the folder where you first run `discovery init`):
```
DOCKER_TAG=develop
```
2. Run `discovery pull` again. This will pull another 15GB of docker images, so if you want to save some HD space, before you do that you can remove the ones you have by typing `docker images` and then run `docker rmi IMAGE_ID` where `IMAGE_ID` are the strings from the previous command from that column.

**Comment by guix77** [comment]
Problem solved for me. I forgot to `getTaskResult` before `decryptTaskResult`... https://github.com/guix77/enigma-secret-access-control/commit/1f1e0019a608626a272f71e6ffb6370f649a00bc
